-- ========================================================
-- Migración: Sistema de Recurrencias (Turnos Fijos)
-- Modificado para usar asociación directa con clase_id
-- ========================================================

-- 1. Agregar columna para usuarios internos
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS es_interno BOOLEAN DEFAULT FALSE;

-- 2. Crear tabla de recurrencias
CREATE TABLE IF NOT EXISTS recurrencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    clase_id BIGINT REFERENCES clases(id) ON DELETE CASCADE,
    dia_semanal INTEGER, -- Opcional, para redundancia o cache visual
    notas TEXT,
    activa BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indice para facilitar las busquedas de repeticion de un usuario
CREATE INDEX IF NOT EXISTS idx_recurrencias_usuario ON recurrencias(usuario_id);
